// This file is generated by icon spritesheet generator

export type IconName =
  | "x"
  | "trash"
  | "tag"
  | "sun"
  | "sprite"
  | "plus"
  | "moon"
  | "minus"
  | "info"
  | "globe"
  | "filter"
  | "computer"
  | "chevron-up"
  | "chevron-down"
  | "check"
  | "bag";

export const iconNames = [
  "x",
  "trash",
  "tag",
  "sun",
  "sprite",
  "plus",
  "moon",
  "minus",
  "info",
  "globe",
  "filter",
  "computer",
  "chevron-up",
  "chevron-down",
  "check",
  "bag",
] as const;
