import {promises as fs} from 'node:fs';
import {glob} from 'glob';
import * as path from 'node:path';

const cwd = process.cwd();
const inputDir = path.join(cwd, 'app/assets/icons/flags');
const flagSvgFiles = glob.sync('*.svg', {
  cwd: inputDir,
});

const countryCodes = flagSvgFiles.map((file) =>
  file.replace(/\.svg$/, ''),
);

async function writeIfChanged(filepath: string, newContent: string) {
  const currentContent = await fs.readFile(filepath, 'utf8');
  if (currentContent !== newContent) {
    return fs.writeFile(filepath, newContent, 'utf8');
  }
}

async function generateTypes({countryCodes}: {countryCodes: string[]}) {
    return `
// This file is generated by npm run build:icons

${countryCodes.map(countryCode => `import ${countryCode} from '../../assets/icons/flags/${countryCode}.svg';`).join('\n')}

export type CountryCode = ${countryCodes.map(countryCode => `'${countryCode}'`).join(' | ')};
export const flagIcons: Record<CountryCode, string> = {
    ${countryCodes.join(', ')}
};
    `
}


const flagTsContent = await generateTypes({countryCodes});
writeIfChanged(path.join('app/components/icons/flags.ts'), flagTsContent)
