saveExact: true
packageManagerStrict: true
minimumReleaseAge: 10800
minimumReleaseAgeExclude:
  - remix
  - "@remix-run/*"
  - "@shopify/hydrogen"
minimumReleaseAgeStrict: true
trustPolicy: no-downgrade
trustPolicyExclude:
  - chokidar@4.0.3
  - semver@6.3.1
