saveExact: true
packageManagerStrict: true
minimumReleaseAge: 10800
minimumReleaseAgeExclude:
  - remix
  - "@remix-run/*"
  - "@shopify/hydrogen"
  - "@hiogawa/vite-plugin-fullstack"
  - vite
  - typescript
  - oxc-parser
minimumReleaseAgeStrict: true
trustPolicy: no-downgrade
trustPolicyExclude:
  - chokidar@4.0.3
  - semver@6.3.1
