import type {Plugin} from 'vite';

/**
 * This plugin removes the hash from the sprite file name generated by createSvgSpritePlugin.
 */
export function removeHashFromSprite(): Plugin {
  return {
    name: 'remove-hash-from-sprite',
    generateBundle(options, bundle) {
      for (const [fileName, file] of Object.entries(bundle)) {
        if (fileName.includes('sprite-') && fileName.endsWith('.svg')) {
          const newFileName = fileName.replace(
            /-([a-zA-Z0-9]{8})\.svg$/,
            '.svg',
          );
          if (newFileName !== fileName) {
            // Rename the file in the bundle
            bundle[newFileName] = {...file, fileName: newFileName};
            delete bundle[fileName];
          }
        }
      }
    },
  };
}
