// This file is generated by icon spritesheet generator

export const iconNames = [
  "youtube",
  "x",
  "twitter",
  "trash",
  "tag",
  "sun",
  "shop-pay",
  "plus",
  "moon",
  "minus",
  "menu",
  "mail",
  "info",
  "globe",
  "github",
  "filter",
  "fast-forward",
  "discord",
  "computer",
  "circle-check",
  "chevron-up",
  "chevron-right",
  "chevron-left",
  "chevron-down",
  "check",
  "cart",
  "bag",
] as const

export type IconName = typeof iconNames[number]
