// This file is generated by icon spritesheet generator

export const iconNames = [
  "x",
  "trash",
  "tag",
  "sun",
  "plus",
  "moon",
  "minus",
  "info",
  "globe",
  "filter",
  "computer",
  "chevron-up",
  "chevron-down",
  "check",
  "bag",
] as const

export type IconName = typeof iconNames[number]
