// This file is generated by npm run build:icons

import ZW from '../../assets/icons/flags/ZW.svg';
import ZM from '../../assets/icons/flags/ZM.svg';
import ZA from '../../assets/icons/flags/ZA.svg';
import YT from '../../assets/icons/flags/YT.svg';
import YE from '../../assets/icons/flags/YE.svg';
import WS from '../../assets/icons/flags/WS.svg';
import WF from '../../assets/icons/flags/WF.svg';
import VU from '../../assets/icons/flags/VU.svg';
import VN from '../../assets/icons/flags/VN.svg';
import VI from '../../assets/icons/flags/VI.svg';
import VG from '../../assets/icons/flags/VG.svg';
import VE from '../../assets/icons/flags/VE.svg';
import VC from '../../assets/icons/flags/VC.svg';
import VA from '../../assets/icons/flags/VA.svg';
import UZ from '../../assets/icons/flags/UZ.svg';
import UY from '../../assets/icons/flags/UY.svg';
import US from '../../assets/icons/flags/US.svg';
import UM from '../../assets/icons/flags/UM.svg';
import UG from '../../assets/icons/flags/UG.svg';
import UA from '../../assets/icons/flags/UA.svg';
import TZ from '../../assets/icons/flags/TZ.svg';
import TW from '../../assets/icons/flags/TW.svg';
import TV from '../../assets/icons/flags/TV.svg';
import TT from '../../assets/icons/flags/TT.svg';
import TR from '../../assets/icons/flags/TR.svg';
import TO from '../../assets/icons/flags/TO.svg';
import TN from '../../assets/icons/flags/TN.svg';
import TM from '../../assets/icons/flags/TM.svg';
import TL from '../../assets/icons/flags/TL.svg';
import TK from '../../assets/icons/flags/TK.svg';
import TJ from '../../assets/icons/flags/TJ.svg';
import TH from '../../assets/icons/flags/TH.svg';
import TG from '../../assets/icons/flags/TG.svg';
import TF from '../../assets/icons/flags/TF.svg';
import TD from '../../assets/icons/flags/TD.svg';
import TC from '../../assets/icons/flags/TC.svg';
import SZ from '../../assets/icons/flags/SZ.svg';
import SY from '../../assets/icons/flags/SY.svg';
import SX from '../../assets/icons/flags/SX.svg';
import SV from '../../assets/icons/flags/SV.svg';
import ST from '../../assets/icons/flags/ST.svg';
import SS from '../../assets/icons/flags/SS.svg';
import SR from '../../assets/icons/flags/SR.svg';
import SO from '../../assets/icons/flags/SO.svg';
import SN from '../../assets/icons/flags/SN.svg';
import SM from '../../assets/icons/flags/SM.svg';
import SL from '../../assets/icons/flags/SL.svg';
import SK from '../../assets/icons/flags/SK.svg';
import SJ from '../../assets/icons/flags/SJ.svg';
import SI from '../../assets/icons/flags/SI.svg';
import SH from '../../assets/icons/flags/SH.svg';
import SG from '../../assets/icons/flags/SG.svg';
import SE from '../../assets/icons/flags/SE.svg';
import SD from '../../assets/icons/flags/SD.svg';
import SC from '../../assets/icons/flags/SC.svg';
import SB from '../../assets/icons/flags/SB.svg';
import SA from '../../assets/icons/flags/SA.svg';
import RW from '../../assets/icons/flags/RW.svg';
import RU from '../../assets/icons/flags/RU.svg';
import RS from '../../assets/icons/flags/RS.svg';
import RO from '../../assets/icons/flags/RO.svg';
import RE from '../../assets/icons/flags/RE.svg';
import QA from '../../assets/icons/flags/QA.svg';
import PY from '../../assets/icons/flags/PY.svg';
import PW from '../../assets/icons/flags/PW.svg';
import PT from '../../assets/icons/flags/PT.svg';
import PS from '../../assets/icons/flags/PS.svg';
import PR from '../../assets/icons/flags/PR.svg';
import PN from '../../assets/icons/flags/PN.svg';
import PM from '../../assets/icons/flags/PM.svg';
import PL from '../../assets/icons/flags/PL.svg';
import PK from '../../assets/icons/flags/PK.svg';
import PH from '../../assets/icons/flags/PH.svg';
import PG from '../../assets/icons/flags/PG.svg';
import PF from '../../assets/icons/flags/PF.svg';
import PE from '../../assets/icons/flags/PE.svg';
import PA from '../../assets/icons/flags/PA.svg';
import OM from '../../assets/icons/flags/OM.svg';
import NZ from '../../assets/icons/flags/NZ.svg';
import NU from '../../assets/icons/flags/NU.svg';
import NR from '../../assets/icons/flags/NR.svg';
import NP from '../../assets/icons/flags/NP.svg';
import NO from '../../assets/icons/flags/NO.svg';
import NL from '../../assets/icons/flags/NL.svg';
import NI from '../../assets/icons/flags/NI.svg';
import NG from '../../assets/icons/flags/NG.svg';
import NF from '../../assets/icons/flags/NF.svg';
import NE from '../../assets/icons/flags/NE.svg';
import NC from '../../assets/icons/flags/NC.svg';
import NA from '../../assets/icons/flags/NA.svg';
import MZ from '../../assets/icons/flags/MZ.svg';
import MY from '../../assets/icons/flags/MY.svg';
import MX from '../../assets/icons/flags/MX.svg';
import MW from '../../assets/icons/flags/MW.svg';
import MV from '../../assets/icons/flags/MV.svg';
import MU from '../../assets/icons/flags/MU.svg';
import MT from '../../assets/icons/flags/MT.svg';
import MS from '../../assets/icons/flags/MS.svg';
import MR from '../../assets/icons/flags/MR.svg';
import MQ from '../../assets/icons/flags/MQ.svg';
import MP from '../../assets/icons/flags/MP.svg';
import MO from '../../assets/icons/flags/MO.svg';
import MN from '../../assets/icons/flags/MN.svg';
import MM from '../../assets/icons/flags/MM.svg';
import ML from '../../assets/icons/flags/ML.svg';
import MK from '../../assets/icons/flags/MK.svg';
import MH from '../../assets/icons/flags/MH.svg';
import MG from '../../assets/icons/flags/MG.svg';
import MF from '../../assets/icons/flags/MF.svg';
import ME from '../../assets/icons/flags/ME.svg';
import MD from '../../assets/icons/flags/MD.svg';
import MC from '../../assets/icons/flags/MC.svg';
import MA from '../../assets/icons/flags/MA.svg';
import LY from '../../assets/icons/flags/LY.svg';
import LV from '../../assets/icons/flags/LV.svg';
import LU from '../../assets/icons/flags/LU.svg';
import LT from '../../assets/icons/flags/LT.svg';
import LS from '../../assets/icons/flags/LS.svg';
import LR from '../../assets/icons/flags/LR.svg';
import LK from '../../assets/icons/flags/LK.svg';
import LI from '../../assets/icons/flags/LI.svg';
import LC from '../../assets/icons/flags/LC.svg';
import LB from '../../assets/icons/flags/LB.svg';
import LA from '../../assets/icons/flags/LA.svg';
import KZ from '../../assets/icons/flags/KZ.svg';
import KY from '../../assets/icons/flags/KY.svg';
import KW from '../../assets/icons/flags/KW.svg';
import KR from '../../assets/icons/flags/KR.svg';
import KP from '../../assets/icons/flags/KP.svg';
import KN from '../../assets/icons/flags/KN.svg';
import KM from '../../assets/icons/flags/KM.svg';
import KI from '../../assets/icons/flags/KI.svg';
import KH from '../../assets/icons/flags/KH.svg';
import KG from '../../assets/icons/flags/KG.svg';
import KE from '../../assets/icons/flags/KE.svg';
import JP from '../../assets/icons/flags/JP.svg';
import JO from '../../assets/icons/flags/JO.svg';
import JM from '../../assets/icons/flags/JM.svg';
import JE from '../../assets/icons/flags/JE.svg';
import IT from '../../assets/icons/flags/IT.svg';
import IS from '../../assets/icons/flags/IS.svg';
import IR from '../../assets/icons/flags/IR.svg';
import IQ from '../../assets/icons/flags/IQ.svg';
import IO from '../../assets/icons/flags/IO.svg';
import IN from '../../assets/icons/flags/IN.svg';
import IM from '../../assets/icons/flags/IM.svg';
import IL from '../../assets/icons/flags/IL.svg';
import IE from '../../assets/icons/flags/IE.svg';
import ID from '../../assets/icons/flags/ID.svg';
import HU from '../../assets/icons/flags/HU.svg';
import HT from '../../assets/icons/flags/HT.svg';
import HR from '../../assets/icons/flags/HR.svg';
import HN from '../../assets/icons/flags/HN.svg';
import HM from '../../assets/icons/flags/HM.svg';
import HK from '../../assets/icons/flags/HK.svg';
import GY from '../../assets/icons/flags/GY.svg';
import GW from '../../assets/icons/flags/GW.svg';
import GU from '../../assets/icons/flags/GU.svg';
import GT from '../../assets/icons/flags/GT.svg';
import GS from '../../assets/icons/flags/GS.svg';
import GR from '../../assets/icons/flags/GR.svg';
import GQ from '../../assets/icons/flags/GQ.svg';
import GP from '../../assets/icons/flags/GP.svg';
import GN from '../../assets/icons/flags/GN.svg';
import GM from '../../assets/icons/flags/GM.svg';
import GL from '../../assets/icons/flags/GL.svg';
import GI from '../../assets/icons/flags/GI.svg';
import GH from '../../assets/icons/flags/GH.svg';
import GG from '../../assets/icons/flags/GG.svg';
import GF from '../../assets/icons/flags/GF.svg';
import GE from '../../assets/icons/flags/GE.svg';
import GD from '../../assets/icons/flags/GD.svg';
import GA from '../../assets/icons/flags/GA.svg';
import FR from '../../assets/icons/flags/FR.svg';
import FO from '../../assets/icons/flags/FO.svg';
import FM from '../../assets/icons/flags/FM.svg';
import FK from '../../assets/icons/flags/FK.svg';
import FJ from '../../assets/icons/flags/FJ.svg';
import FI from '../../assets/icons/flags/FI.svg';
import ET from '../../assets/icons/flags/ET.svg';
import ES from '../../assets/icons/flags/ES.svg';
import ER from '../../assets/icons/flags/ER.svg';
import EH from '../../assets/icons/flags/EH.svg';
import EG from '../../assets/icons/flags/EG.svg';
import EE from '../../assets/icons/flags/EE.svg';
import EC from '../../assets/icons/flags/EC.svg';
import DZ from '../../assets/icons/flags/DZ.svg';
import DO from '../../assets/icons/flags/DO.svg';
import DM from '../../assets/icons/flags/DM.svg';
import DK from '../../assets/icons/flags/DK.svg';
import DJ from '../../assets/icons/flags/DJ.svg';
import DE from '../../assets/icons/flags/DE.svg';
import CZ from '../../assets/icons/flags/CZ.svg';
import CY from '../../assets/icons/flags/CY.svg';
import CX from '../../assets/icons/flags/CX.svg';
import CW from '../../assets/icons/flags/CW.svg';
import CV from '../../assets/icons/flags/CV.svg';
import CU from '../../assets/icons/flags/CU.svg';
import CR from '../../assets/icons/flags/CR.svg';
import CO from '../../assets/icons/flags/CO.svg';
import CN from '../../assets/icons/flags/CN.svg';
import CM from '../../assets/icons/flags/CM.svg';
import CL from '../../assets/icons/flags/CL.svg';
import CK from '../../assets/icons/flags/CK.svg';
import CI from '../../assets/icons/flags/CI.svg';
import CH from '../../assets/icons/flags/CH.svg';
import CG from '../../assets/icons/flags/CG.svg';
import CF from '../../assets/icons/flags/CF.svg';
import CD from '../../assets/icons/flags/CD.svg';
import CC from '../../assets/icons/flags/CC.svg';
import CA from '../../assets/icons/flags/CA.svg';
import BZ from '../../assets/icons/flags/BZ.svg';
import BY from '../../assets/icons/flags/BY.svg';
import BW from '../../assets/icons/flags/BW.svg';
import BV from '../../assets/icons/flags/BV.svg';
import BT from '../../assets/icons/flags/BT.svg';
import BS from '../../assets/icons/flags/BS.svg';
import BR from '../../assets/icons/flags/BR.svg';
import BO from '../../assets/icons/flags/BO.svg';
import BN from '../../assets/icons/flags/BN.svg';
import BM from '../../assets/icons/flags/BM.svg';
import BL from '../../assets/icons/flags/BL.svg';
import BJ from '../../assets/icons/flags/BJ.svg';
import BI from '../../assets/icons/flags/BI.svg';
import BH from '../../assets/icons/flags/BH.svg';
import BG from '../../assets/icons/flags/BG.svg';
import BF from '../../assets/icons/flags/BF.svg';
import BE from '../../assets/icons/flags/BE.svg';
import BD from '../../assets/icons/flags/BD.svg';
import BB from '../../assets/icons/flags/BB.svg';
import BA from '../../assets/icons/flags/BA.svg';
import AZ from '../../assets/icons/flags/AZ.svg';
import AX from '../../assets/icons/flags/AX.svg';
import AW from '../../assets/icons/flags/AW.svg';
import AU from '../../assets/icons/flags/AU.svg';
import AT from '../../assets/icons/flags/AT.svg';
import AS from '../../assets/icons/flags/AS.svg';
import AR from '../../assets/icons/flags/AR.svg';
import AQ from '../../assets/icons/flags/AQ.svg';
import AO from '../../assets/icons/flags/AO.svg';
import AM from '../../assets/icons/flags/AM.svg';
import AL from '../../assets/icons/flags/AL.svg';
import AI from '../../assets/icons/flags/AI.svg';
import AG from '../../assets/icons/flags/AG.svg';
import AF from '../../assets/icons/flags/AF.svg';
import AE from '../../assets/icons/flags/AE.svg';
import AD from '../../assets/icons/flags/AD.svg';

export type CountryCode =
  | 'ZW'
  | 'ZM'
  | 'ZA'
  | 'YT'
  | 'YE'
  | 'WS'
  | 'WF'
  | 'VU'
  | 'VN'
  | 'VI'
  | 'VG'
  | 'VE'
  | 'VC'
  | 'VA'
  | 'UZ'
  | 'UY'
  | 'US'
  | 'UM'
  | 'UG'
  | 'UA'
  | 'TZ'
  | 'TW'
  | 'TV'
  | 'TT'
  | 'TR'
  | 'TO'
  | 'TN'
  | 'TM'
  | 'TL'
  | 'TK'
  | 'TJ'
  | 'TH'
  | 'TG'
  | 'TF'
  | 'TD'
  | 'TC'
  | 'SZ'
  | 'SY'
  | 'SX'
  | 'SV'
  | 'ST'
  | 'SS'
  | 'SR'
  | 'SO'
  | 'SN'
  | 'SM'
  | 'SL'
  | 'SK'
  | 'SJ'
  | 'SI'
  | 'SH'
  | 'SG'
  | 'SE'
  | 'SD'
  | 'SC'
  | 'SB'
  | 'SA'
  | 'RW'
  | 'RU'
  | 'RS'
  | 'RO'
  | 'RE'
  | 'QA'
  | 'PY'
  | 'PW'
  | 'PT'
  | 'PS'
  | 'PR'
  | 'PN'
  | 'PM'
  | 'PL'
  | 'PK'
  | 'PH'
  | 'PG'
  | 'PF'
  | 'PE'
  | 'PA'
  | 'OM'
  | 'NZ'
  | 'NU'
  | 'NR'
  | 'NP'
  | 'NO'
  | 'NL'
  | 'NI'
  | 'NG'
  | 'NF'
  | 'NE'
  | 'NC'
  | 'NA'
  | 'MZ'
  | 'MY'
  | 'MX'
  | 'MW'
  | 'MV'
  | 'MU'
  | 'MT'
  | 'MS'
  | 'MR'
  | 'MQ'
  | 'MP'
  | 'MO'
  | 'MN'
  | 'MM'
  | 'ML'
  | 'MK'
  | 'MH'
  | 'MG'
  | 'MF'
  | 'ME'
  | 'MD'
  | 'MC'
  | 'MA'
  | 'LY'
  | 'LV'
  | 'LU'
  | 'LT'
  | 'LS'
  | 'LR'
  | 'LK'
  | 'LI'
  | 'LC'
  | 'LB'
  | 'LA'
  | 'KZ'
  | 'KY'
  | 'KW'
  | 'KR'
  | 'KP'
  | 'KN'
  | 'KM'
  | 'KI'
  | 'KH'
  | 'KG'
  | 'KE'
  | 'JP'
  | 'JO'
  | 'JM'
  | 'JE'
  | 'IT'
  | 'IS'
  | 'IR'
  | 'IQ'
  | 'IO'
  | 'IN'
  | 'IM'
  | 'IL'
  | 'IE'
  | 'ID'
  | 'HU'
  | 'HT'
  | 'HR'
  | 'HN'
  | 'HM'
  | 'HK'
  | 'GY'
  | 'GW'
  | 'GU'
  | 'GT'
  | 'GS'
  | 'GR'
  | 'GQ'
  | 'GP'
  | 'GN'
  | 'GM'
  | 'GL'
  | 'GI'
  | 'GH'
  | 'GG'
  | 'GF'
  | 'GE'
  | 'GD'
  | 'GA'
  | 'FR'
  | 'FO'
  | 'FM'
  | 'FK'
  | 'FJ'
  | 'FI'
  | 'ET'
  | 'ES'
  | 'ER'
  | 'EH'
  | 'EG'
  | 'EE'
  | 'EC'
  | 'DZ'
  | 'DO'
  | 'DM'
  | 'DK'
  | 'DJ'
  | 'DE'
  | 'CZ'
  | 'CY'
  | 'CX'
  | 'CW'
  | 'CV'
  | 'CU'
  | 'CR'
  | 'CO'
  | 'CN'
  | 'CM'
  | 'CL'
  | 'CK'
  | 'CI'
  | 'CH'
  | 'CG'
  | 'CF'
  | 'CD'
  | 'CC'
  | 'CA'
  | 'BZ'
  | 'BY'
  | 'BW'
  | 'BV'
  | 'BT'
  | 'BS'
  | 'BR'
  | 'BO'
  | 'BN'
  | 'BM'
  | 'BL'
  | 'BJ'
  | 'BI'
  | 'BH'
  | 'BG'
  | 'BF'
  | 'BE'
  | 'BD'
  | 'BB'
  | 'BA'
  | 'AZ'
  | 'AX'
  | 'AW'
  | 'AU'
  | 'AT'
  | 'AS'
  | 'AR'
  | 'AQ'
  | 'AO'
  | 'AM'
  | 'AL'
  | 'AI'
  | 'AG'
  | 'AF'
  | 'AE'
  | 'AD';
export const flagIcons: Record<CountryCode, string> = {
  ZW,
  ZM,
  ZA,
  YT,
  YE,
  WS,
  WF,
  VU,
  VN,
  VI,
  VG,
  VE,
  VC,
  VA,
  UZ,
  UY,
  US,
  UM,
  UG,
  UA,
  TZ,
  TW,
  TV,
  TT,
  TR,
  TO,
  TN,
  TM,
  TL,
  TK,
  TJ,
  TH,
  TG,
  TF,
  TD,
  TC,
  SZ,
  SY,
  SX,
  SV,
  ST,
  SS,
  SR,
  SO,
  SN,
  SM,
  SL,
  SK,
  SJ,
  SI,
  SH,
  SG,
  SE,
  SD,
  SC,
  SB,
  SA,
  RW,
  RU,
  RS,
  RO,
  RE,
  QA,
  PY,
  PW,
  PT,
  PS,
  PR,
  PN,
  PM,
  PL,
  PK,
  PH,
  PG,
  PF,
  PE,
  PA,
  OM,
  NZ,
  NU,
  NR,
  NP,
  NO,
  NL,
  NI,
  NG,
  NF,
  NE,
  NC,
  NA,
  MZ,
  MY,
  MX,
  MW,
  MV,
  MU,
  MT,
  MS,
  MR,
  MQ,
  MP,
  MO,
  MN,
  MM,
  ML,
  MK,
  MH,
  MG,
  MF,
  ME,
  MD,
  MC,
  MA,
  LY,
  LV,
  LU,
  LT,
  LS,
  LR,
  LK,
  LI,
  LC,
  LB,
  LA,
  KZ,
  KY,
  KW,
  KR,
  KP,
  KN,
  KM,
  KI,
  KH,
  KG,
  KE,
  JP,
  JO,
  JM,
  JE,
  IT,
  IS,
  IR,
  IQ,
  IO,
  IN,
  IM,
  IL,
  IE,
  ID,
  HU,
  HT,
  HR,
  HN,
  HM,
  HK,
  GY,
  GW,
  GU,
  GT,
  GS,
  GR,
  GQ,
  GP,
  GN,
  GM,
  GL,
  GI,
  GH,
  GG,
  GF,
  GE,
  GD,
  GA,
  FR,
  FO,
  FM,
  FK,
  FJ,
  FI,
  ET,
  ES,
  ER,
  EH,
  EG,
  EE,
  EC,
  DZ,
  DO,
  DM,
  DK,
  DJ,
  DE,
  CZ,
  CY,
  CX,
  CW,
  CV,
  CU,
  CR,
  CO,
  CN,
  CM,
  CL,
  CK,
  CI,
  CH,
  CG,
  CF,
  CD,
  CC,
  CA,
  BZ,
  BY,
  BW,
  BV,
  BT,
  BS,
  BR,
  BO,
  BN,
  BM,
  BL,
  BJ,
  BI,
  BH,
  BG,
  BF,
  BE,
  BD,
  BB,
  BA,
  AZ,
  AX,
  AW,
  AU,
  AT,
  AS,
  AR,
  AQ,
  AO,
  AM,
  AL,
  AI,
  AG,
  AF,
  AE,
  AD,
};
